name: Deploy static HTML

on:
  push:
    branches:
      - main

jobs:
  deploy job:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display files
        run: ls

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./